// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfjeyuttyjzypuqiwoqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmamV5dXR0eWp6eXB1cWl3b3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODgzMDUsImV4cCI6MjA1OTQ2NDMwNX0.EKXXs55jo_iss0_bSQlwxzz9BAJ1Akx_UJhXeGPXmzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);